### PR TITLE
Sfsw 2260 new component accessibility adjustments

### PR DESCRIPTION
**Pull request by mattb-hippo**
Changes:

* removed emboldening from Page Contents header as directed
* change page contents header font size to be specified as rem not px, as directed
* left-aligned content of Info Box as directed

### CODE REVIEW

**Comment by Maria-C1** [comment]
@mattb-hippo  Should the text in the info box fill the width of it? On some device views it cuts it off part-way:
Screenshot 2024-11-20 162436

**Comment by mattb-hippo** [comment]
> @mattb-hippo Should the text in the info box fill the width of it? On some device views it cuts it off part-way

Have pushed a fix

**Review by Maria-C1 — APPROVED** [review]

**Pull request merged**
