### PR TITLE
Updated Regression UI Tests

### PR DESCRIPTION
**Pull request by MartinBelton-gov**
Updated Regression UI Tests

### CODE REVIEW

**Review by killij — CHANGES_REQUESTED** [review]
Can we confirm if Areas of Practice have been removed? If so can we remove the tests pls.

**Comment by MartinBelton-gov** [comment]
> Can we confirm if Areas of Practice have been removed? If so can we remove the tests pls.

MAB - Areas of Practice still exist. Have removed the skip, and tested OK against preprod

**Review by killij — APPROVED** [review]

**Pull request merged**
